- hosts: localhost
  sudo: yes

  tasks:
     - name: make locale
       action: command locale-gen en_GB.utf8
     - name: -> install packages
       action: apt pkg=${item} state=installed update_cache=yes
       tags: install_basic
       with_items:
          - htop
          - git
          - python-dev
          - build-essential
          - libxml2-dev
          - libxslt1-dev
          - libpq-dev
          - language-pack-en
          - ufw
          - python-psycopg2
          - nginx  
          - apache2  
          - libapache2-mod-wsgi 
          - libpq5
          - postgresql-client-common 
          - postgresql-client-9.1
          - python-virtualenv

